# check compilation with previous versions of ocaml

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    paths:
      - '.github/workflows/emacs.yml'
      - 'editors/emacs/**'
  workflow_dispatch:

jobs:
  test_compile:
    strategy:
      fail-fast: false
      matrix:
        # 5.3.0: 08/01/2025
        # 5.2.1: 18/11/2024
        # 5.1.1: 08/12/2023
        # 5.0.0: 16/12/2022
        # 4.14.2: 15/03/2024
        # 4.13.1: 01/10/2021
        # 4.12.1: 24/02/2021
        # 4.11.2: 24/02/2021
        # 4.10.2: 18/12/2020
        # 4.09.1: 16/03/2020
        eglot: [1.7]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build lambdapi-mode
        run: make -C editors/emacs dist
      - name: install lambdapi-mode
        run: |
          chmod +x installAndLaunch.sh
          ./installAndLaunch.sh lambdapi-mode 1.1.0 /snap/bin/emacs 
        working-directory: editors/emacs/